# Generated by Django 4.1.5 on 2023-01-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="cratedAt", new_name="createdAt",
        ),
    ]
