# Generated by Django 4.1.5 on 2023-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_cratedat_order_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
