# Generated by Django 4.1.5 on 2023-10-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.jpg", null=True, upload_to=""
            ),
        ),
    ]
